@startuml Diagrama

class Juego

class Jugador
class Enemigo
class Interfaz 
class EstadoJuego
class Logica

class Mapa
class Casilla
class Movimiento
class Personaje
class Vaca
class Fantasma
class Nivel

Juego "1" *-- "1" Jugador
Juego "1" *-- "1" Mapa
Mapa "1" *-- "100" Casilla
Mapa "1" *-- "1" Enemigo
Enemigo --|> Fantasma
Jugador "1" o-- "1" Personaje
Mapa "1" *-- "*" Nivel
Vaca "1" *-- "*" Movimiento
Personaje --|> Vaca 
Juego "1" o-- "1"EstadoJuego
Juego "1" *-- "1" Logica
Juego "1" *-- "1" Interfaz

@enduml